services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "18083:18083"
    volumes:
      - ./data/emqx/data:/opt/emqx/data
      - ./data/emqx/log:/opt/emqx/log
    networks:
      rats-net:
        ipv4_address: 172.18.0.5
    depends_on:
      - timescaledb
    restart: unless-stopped
  
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Rocketry2526
      - PGDATA=/pgdata
    volumes:
      - ./data/timescaledb:/pgdata
    networks:
      rats-net:
        ipv4_address: 172.18.0.2
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=125ms
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      rats-net:
        ipv4_address: 172.18.0.3
    depends_on: 
      - timescaledb
    restart: unless-stopped
  
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - ./data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      rats-net:
        ipv4_address: 172.18.0.4
    restart: unless-stopped
  
  go2rtc:
    image: alexxit/go2rtc
    network_mode: host
    privileged: true        
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    volumes:
      - ./data/go2rtc:/config

  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    environment:
      - TZ=America/New_York
    volumes:
      - ./data/homeassistant:/config
    restart: unless-stopped

networks:
  rats-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24